name: lonefy
description: Musical Player
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mesh_gradient: ^1.3.8
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_translation: ^0.20.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/Interface/Assets/Images/English.png
    - lib/Interface/Assets/Images/Russia.png
    - lib/Interface/Assets/Images/France.png
    - lib/Interface/Assets/Images/Google.png
    - lib/Interface/Assets/Images/Facebook.png

  fonts:
    - family: lonefyBold
      fonts: [ { asset: lib/Interface/Assets/Fonts/lonefyBold.ttf } ]
flutter_intl:
  enabled: true
