name: lonefy
description: Musical Player
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  appwrite: ^15.0.0
  auto_route: ^9.3.0+1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hugeicons: ^0.0.10
  intl: ^0.20.2
  mesh_gradient: ^1.3.8
  provider: ^6.1.4
  extended_image: ^10.0.1
  image_picker: ^1.1.2
  image: ^4.0.17
  flutter_rating_bar: ^4.0.1

dependency_overrides:
  flutter_web_auth_2: 5.0.0-alpha.2
dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  intl_translation: ^0.20.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/Interface/Assets/Images/English.png
    - lib/Interface/Assets/Images/Russia.png
    - lib/Interface/Assets/Images/France.png
    - lib/Interface/Assets/Images/Google.png
    - lib/Interface/Assets/Images/Facebook.png
    - lib/Interface/Assets/Images/unknown.png

  fonts:
    - family: lonefyBold
      fonts: [ { asset: lib/Interface/Assets/Fonts/lonefyBold.ttf } ]
flutter_intl:
  enabled: true
